async function loadStats() {
  const user = document.getElementById("username").value;
  if (!user) return;

  // Load JSON file generated by GitHub Actions
  const res = await fetch(`data/${user}.json`);
  if (!res.ok) {
    document.getElementById("results").innerHTML = "<p>User not found.</p>";
    return;
  }

  const data = await res.json();
  const container = document.getElementById("results");
  container.innerHTML = "";

  for (const mode in LEVEL_TABLES) {
    const stats = data[mode];
    if (!stats) continue;

    const xp = stats.xp || 0;
    const level = calculateLevel(mode, xp);
    const max = LEVEL_TABLES[mode].length;

    const prevXP = LEVEL_TABLES[mode][level - 2] || 0;
    const nextXP = LEVEL_TABLES[mode][level - 1] || LEVEL_TABLES[mode][max - 1];

    const progress = ((xp - prevXP) / (nextXP - prevXP)) * 100;

    container.innerHTML += `
      <div class="card">
        <h2>${MODE_NAMES[mode]}</h2>
        <p>Level: ${level} / ${max}</p>
        <p>XP: ${xp.toLocaleString()}</p>
        <div class="progress">
          <div class="progress-bar" style="width:${progress}%"></div>
        </div>
      </div>
    `;
  }
}
