name: Fetch Hive User Stats

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Hive username"
        required: true
        type: string

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Hive Stats
      run: |
        USER="${{ github.event.inputs.username }}"
        mkdir -p data
        curl -s "https://api.playhive.com/v0/game/all/all/$USER" > data/$USER.json

    - name: Commit results
      env:
        TOKEN: ${{ secrets.WEB_TOKEN }}
      run: |
        USER="${{ github.event.inputs.username }}"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/$USER.json
        git commit -m "Updated stats for $USER" || exit 0
        git push https://$TOKEN@github.com/raid2256/Hive-Progress-Tracker-Website.git HEAD:main
